# -*- coding: utf-8 -*-
"""Projek_DataScience _Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iB_8_ieVPtLmgeLREFWRggaiYcCuNrAB

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1: Kecamatan mana yang menghasilkan sampah paling banyak?
- Pertanyaan 2: Jenis sampah apa yang paling sering muncul dan bagaimana metode pengelolaan terbaiknya?
- Pertanyaan 3: Apakah cuaca mempengaruhi jumlah berat sampah yang dihasilkan?

### Insight:
Pada tahap ini, pertanyaan-pertanyaan bisnis telah diidentifikasi untuk memandu analisis data sampah. Pertanyaan-pertanyaan ini akan fokus pada identifikasi kecamatan dengan volume sampah tertinggi, jenis sampah yang paling umum beserta metode pengelolaannya, dan dampak cuaca terhadap jumlah sampah. Jawaban atas pertanyaan-pertanyaan ini akan memberikan dasar untuk rekomendasi pengelolaan sampah yang lebih efektif.

## Import Library/Packages yang Digunakan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive

sns.set_style('whitegrid')

drive.mount('/content/drive')

"""## Data Wrangling

### Gathering Data
"""

df = pd.read_csv('/content/dataset_sampah_mentah_realistis_2018_2025.csv')

display(df.head())

"""### Insight:
Proses pengumpulan data melibatkan pemuatan dataset 'dataset_sampah_mentah_realistis_2018_2025.csv' ke dalam DataFrame pandas. Dataset ini berisi data historis sampah dari tahun 2018 hingga 2025, yang akan digunakan untuk menjawab pertanyaan bisnis yang telah ditetapkan. Tahap ini krusial untuk memastikan ketersediaan data yang relevan sebelum melanjutkan ke analisis lebih dalam.

### Assessing Data
"""

print("Informasi Dataset")
display(df.info())

print("\nUkuran Dataset")
print(df.shape)

print("\nStatistik Deskriptif")
display(df.describe())

print("\nMissing Value")
display(df.isnull().sum())

print("\nData Duplikat")
print(df.duplicated().sum())

"""### Insight:
- **Informasi Dataset:** Ditemukan adanya missing values pada beberapa kolom seperti `berat_kg`, `volume_liter`, `moisture_level`, `recyclable`, `sumber`, `cuaca`, `suhu_celsius`, dan `catatan_petugas`.
- **Ukuran Dataset:** Dataset memiliki 369.214 baris dan 19 kolom.
- **Statistik Deskriptif:** Memberikan gambaran umum distribusi data numerik.
- **Missing Value:** Konfirmasi kembali jumlah missing values per kolom.
- **Data Duplikat:** Ditemukan adanya 6.661 data duplikat yang perlu ditangani.

### Cleaning Data

### Duplicate value
"""

jumlah_duplikat = df.duplicated().sum()
print(f"Ditemukan {jumlah_duplikat} baris data duplikat.")

if jumlah_duplikat > 0:
    df.drop_duplicates(inplace=True)
    print("-> Data duplikat berhasil dihapus!")

"""# Insight:
 * Deteksi Data: Mengidentifikasi dan menghitung total baris data yang sama persis (duplikat) di dalam dataset, yang dalam kasus ini terdeteksi sebanyak 6.661 baris.

* Efisiensi Kode: Menggunakan fungsi kondisional (if) untuk memastikan proses penghapusan hanya dilakukan jika sistem benar-benar menemukan adanya data ganda.

* Pembersihan Data: Menghapus baris data duplikat secara langsung pada dataset utama (inplace=True) tanpa membuat salinan baru, sehingga menghemat penggunaan memori.

* Integritas Data: Memastikan setiap baris data yang tersisa di dalam dataset adalah unik untuk mencegah terjadinya perhitungan ganda (double-counting) atau bias pada hasil analisis dan kesimpulan nanti.

# Missing Value
"""

df.drop_duplicates(inplace=True)

numerik = [
    'berat_kg',
    'volume_liter',
    'moisture_level',
    'suhu_celsius'
]

kategori = [
    'recyclable',
    'sumber',
    'cuaca',
    'catatan_petugas'
]

for kolom in numerik:
    df[kolom] = df[kolom].fillna(
        df[kolom].median()
    )

for kolom in kategori:
    df[kolom] = df[kolom].fillna(
        df[kolom].mode()[0]
    )

print("Data Setelah Cleaning")
display(df.isnull().sum())

"""### Insight:
Setelah proses cleaning data, yaitu penghapusan duplikat dan pengisian nilai yang hilang (`NaN`) untuk kolom numerik dengan median dan kolom kategorikal dengan modus, kini tidak ada lagi missing values dalam dataset. Ini memastikan data siap untuk analisis lebih lanjut.

# Feature Engginering
"""

df['kepadatan'] = df['berat_kg'] / (df['volume_liter'] + 0.01)

df['periode'] = pd.to_datetime(df['tahun'].astype(str) + '-' + df['bulan'].astype(str).str.zfill(2) + '-01')

batas_bawah = df['estimasi_nilai_daur_ulang_rp'].quantile(0.33)
batas_atas = df['estimasi_nilai_daur_ulang_rp'].quantile(0.66)

def kategori_nilai(nilai):
    if nilai <= batas_bawah: return 'Rendah'
    elif nilai <= batas_atas: return 'Sedang'
    else: return 'Tinggi'

df['kategori_nilai_ekonomi'] = df['estimasi_nilai_daur_ulang_rp'].apply(kategori_nilai)
print(df.head())

"""# Insight :
Pada tahap *Feature Engineering*, kita telah berhasil menciptakan 3 fitur (kolom) baru yang memberikan nilai tambah signifikan untuk analisis lanjutan maupun pemodelan *Machine Learning*:

1. **`kepadatan` (Density Sampah):** Fitur ini didapatkan dari pembagian `berat_kg` dengan `volume_liter`.
   * **Makna Bisnis:** Mengetahui kepadatan sangat krusial untuk logistik. Sampah yang berat tapi volumenya kecil (kepadatan tinggi) membutuhkan penanganan armada yang berbeda dibandingkan sampah ringan namun memakan banyak tempat (kepadatan rendah). Ini membantu optimalisasi ruang di dalam truk pengangkut.

2. **`periode` (Format Waktu Time-Series):** Menggabungkan kolom `tahun` dan `bulan` menjadi satu format tanggal standar (`YYYY-MM-DD`).
   * **Makna Bisnis:** Memudahkan kita untuk melakukan analisis tren waktu (*Time-Series Analysis*). Dengan format ini, kita bisa melihat pergerakan visualisasi data dari waktu ke waktu dengan lebih mulus (misalnya: apakah ada lonjakan volume sampah di bulan-bulan tertentu dari tahun 2018 hingga 2025).

3. **`kategori_nilai_ekonomi` (Segmentasi Potensi Daur Ulang):** Mengubah nilai numerik `estimasi_nilai_daur_ulang_rp` menjadi kategori diskrit ('Rendah', 'Sedang', 'Tinggi') menggunakan perhitungan persentil (*quantile*).
   * **Makna Bisnis:** Fitur ini sangat berguna untuk pengambilan keputusan strategis. Daripada melihat angka rupiah yang acak, pemangku kepentingan (seperti pengelola bank sampah) bisa langsung memfilter dan memprioritaskan jenis atau wilayah mana yang menghasilkan sampah dengan kategori "Tinggi" untuk dimaksimalkan potensi ekonomi sirkularnya.


"""

df['rasio_kelembaban_berat'] = (
    df['moisture_level'] / (df['berat_kg'] + 0.01)
)

df['kategori_suhu'] = pd.cut(
    df['suhu_celsius'],
    bins=[0, 25, 35, 100],
    labels=['Dingin', 'Normal', 'Panas']
)

df['efisiensi_ruang'] = (
    df['volume_liter'] / (df['berat_kg'] + 0.01)
)

df['cuaca_encoded'] = df['cuaca'].astype('category').cat.codes

df['kuartal'] = (
    (df['bulan'] - 1) // 3
) + 1

"""### Insight:
Kita telah berhasil menambahkan 5 fitur (kolom) baru yang memberikan nilai tambah signifikan untuk analisis lanjutan maupun pemodelan *Machine Learning*:

1.  **`rasio_kelembaban_berat` (Moisture-to-Weight Ratio):** Fitur ini didapatkan dari pembagian `moisture_level` dengan `berat_kg`.
    *   **Makna Bisnis:** Rasio ini penting untuk memahami karakteristik sampah, terutama dalam proses pengolahan seperti pengomposan atau insinerasi. Sampah dengan rasio kelembaban-berat tinggi mungkin memerlukan penanganan khusus untuk mengurangi kadar air sebelum diproses lebih lanjut, yang dapat memengaruhi biaya operasional.

2.  **`kategori_suhu` (Temperature Categories):** Mengkategorikan suhu (`suhu_celsius`) menjadi 'Dingin', 'Normal', atau 'Panas' berdasarkan rentang tertentu.
    *   **Makna Bisnis:** Fitur kategorikal ini membantu mengidentifikasi bagaimana suhu lingkungan dapat berkorelasi dengan jumlah atau jenis sampah yang dihasilkan, atau bahkan kondisi dekomposisi sampah. Ini bisa menjadi faktor penting dalam perencanaan pengumpulan sampah dan pengelolaan fasilitas.

3.  **`efisiensi_ruang` (Space Efficiency):** Fitur ini menghitung seberapa efisien volume terisi oleh berat sampah, didapatkan dari pembagian `volume_liter` dengan `berat_kg`.
    *   **Makna Bisnis:** Mirip dengan kepadatan, efisiensi ruang memberikan perspektif terbalik. Ini membantu dalam mengoptimalkan kapasitas truk pengangkut atau tempat penampungan sementara. Sampah dengan efisiensi ruang tinggi (volume besar, berat ringan) memerlukan pertimbangan logistik yang berbeda.

4.  **`cuaca_encoded` (Encoded Weather):** Mengubah fitur kategorikal `cuaca` menjadi representasi numerik menggunakan label encoding.
    *   **Makna Bisnis:** Fitur ini penting untuk model machine learning yang umumnya membutuhkan input numerik. Dengan mengkodekan cuaca, kita dapat menganalisis dan memodelkan dampak cuaca terhadap volume atau jenis sampah secara kuantitatif, tanpa perlu mengkhawatirkan format data non-numerik.

5.  **`kuartal` (Quarter of the Year):** Mengidentifikasi kuartal tahun (1, 2, 3, 4) berdasarkan bulan.
    *   **Makna Bisnis:** Fitur ini memungkinkan analisis tren musiman yang lebih granular. Dengan mengetahui kuartal, kita dapat mengidentifikasi pola peningkatan atau penurunan volume sampah pada periode tertentu dalam setahun, yang dapat membantu dalam alokasi sumber daya dan perencanaan strategis jangka pendek.

# Export Data Bersih
"""

clean_file_path = '/content/drive/MyDrive/Dataset/Dataset_Sampah_Cleaned_2018_2025.csv'
df.to_csv(clean_file_path, index=False)
print(f"\nData bersih berhasil disimpan di:\n{clean_file_path}")

"""### Exploratory Data Analysis (EDA)"""

# EDA Pertanyaan 1: Kecamatan penghasil sampah paling banyak (berdasarkan total berat)
sampah_per_kecamatan = df.groupby('kecamatan')['berat_kg'].sum().sort_values(ascending=False).reset_index()
print("--- Top 10 Kecamatan Penghasil Sampah Terbesar (Total Kg) ---")
display(sampah_per_kecamatan.head(10))

# EDA Pertanyaan 2: Jenis sampah yang paling sering muncul
jenis_sampah_freq = df['jenis_sampah'].value_counts().reset_index()
jenis_sampah_freq.columns = ['jenis_sampah', 'jumlah_kemunculan']
print("\n--- Frekuensi Kemunculan Jenis Sampah ---")
display(jenis_sampah_freq)

# Melihat hubungan antara jenis sampah dominan dengan metode pengelolaan yang digunakan
pengelolaan_organik = df[df['jenis_sampah'] == 'organik']['metode_pengelolaan'].value_counts().reset_index()
print("\n--- Metode Pengelolaan untuk Sampah Organik (Jenis Terbanyak) ---")
display(pengelolaan_organik)

# EDA Pertanyaan 3: Rata-rata berat sampah berdasarkan kondisi cuaca
berat_per_cuaca = df.groupby('cuaca')['berat_kg'].mean().sort_values(ascending=False).reset_index()
print("\n--- Rata-rata Berat Sampah (Kg) per Kondisi Cuaca ---")
display(berat_per_cuaca)

"""### Insight:
Dari hasil EDA awal, ditemukan beberapa poin penting:

*   **Kecamatan Penyumbang Sampah Terbesar:** Kecamatan `Cilandak`, `Pasar Minggu`, dan `Cengkareng` secara konsisten menjadi tiga besar penyumbang berat sampah terbanyak. Hal ini mengindikasikan bahwa wilayah-wilayah ini memerlukan perhatian khusus dalam strategi pengelolaan sampah.

*   **Jenis Sampah Dominan:** `Organik` adalah jenis sampah yang paling sering muncul, diikuti oleh `kertas` dan `plastik`. Ini menyoroti pentingnya fokus pada pengelolaan sampah organik (misalnya melalui pengomposan atau biogas) dan pengembangan program daur ulang yang efektif untuk sampah anorganik.

*   **Metode Pengelolaan Sampah Organik:** Untuk sampah organik, metode pengelolaan yang paling umum adalah `bank sampah`, `dibakar`, dan `daur ulang`. Menariknya, metode `kompos` dan `TPA` juga memiliki proporsi yang signifikan.

*   **Pengaruh Cuaca:** Rata-rata berat sampah tidak menunjukkan perbedaan yang signifikan antar kondisi cuaca (`cerah`, `hujan`, `mendung`). Meskipun ada fluktuasi kecil, cuaca tampaknya bukan faktor utama yang mempengaruhi volume total sampah.

### Visualization & Explanatory Analysis

### Pertanyaan 1 : Kecamatan mana yang menghasilkan sampah paling banyak?
"""

plt.figure(figsize=(12, 6))
# Mengambil 10 kecamatan teratas
sns.barplot(
    x='berat_kg',
    y='kecamatan',
    data=sampah_per_kecamatan.head(10),
    palette='Reds_r'
)
plt.title('Top 10 Kecamatan Penyumbang Sampah Terbesar', fontsize=15, pad=15)
plt.xlabel('Total Berat Sampah (Kg)')
plt.ylabel('Kecamatan')
plt.tight_layout()
plt.show()

"""### Insight:
Dari analisis pertanyaan pertama, `Kecamatan mana yang menghasilkan sampah paling banyak?`, terlihat bahwa **Cilandak** adalah kecamatan yang menghasilkan total berat sampah tertinggi, diikuti oleh Pasar Minggu dan Cengkareng. Ini mengindikasikan bahwa upaya pengelolaan sampah mungkin perlu lebih difokuskan di area-area ini.

### Pertanyaan 2 : Jenis sampah apa yang paling sering muncul dan bagaimana metode pengelolaan terbaiknya?
"""

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Grafik 1: Proporsi Jenis Sampah
sns.barplot(
    x='jenis_sampah',
    y='jumlah_kemunculan',
    data=jenis_sampah_freq,
    palette='viridis',
    ax=axes[0]
)
axes[0].set_title('Distribusi Jenis Sampah', fontsize=14)
axes[0].set_xlabel('Jenis Sampah')
axes[0].set_ylabel('Frekuensi Kemunculan')
axes[0].tick_params(axis='x', rotation=45)

# Grafik 2: Metode Pengelolaan khusus Organik
sns.barplot(
    x='metode_pengelolaan',
    y='count',
    data=pengelolaan_organik,
    palette='Greens_r',
    ax=axes[1]
)
axes[1].set_title('Metode Pengelolaan Sampah Organik', fontsize=14)
axes[1].set_xlabel('Metode Pengelolaan')
axes[1].set_ylabel('Jumlah Kasus')
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""### Insight:
Untuk pertanyaan kedua, `Jenis sampah apa yang paling sering muncul dan bagaimana metode pengelolaan terbaiknya?`, grafik menunjukkan bahwa `organik` adalah jenis sampah yang paling dominan dengan jumlah jauh di atas jenis sampah lainnya. Metode pengelolaan yang paling sering tercatat untuk sampah organik adalah `bank sampah`, `dibakar`, dan `daur ulang`, dengan `kompos` juga memiliki proporsi yang signifikan. Ini menunjukkan bahwa fokus pengelolaan sampah organik saat ini mencakup berbagai pendekatan. Jenis sampah lain seperti `kertas` dan `plastik` juga signifikan, menunjukkan pentingnya program daur ulang dan pemilahan sampah yang efektif.

### Pertanyaan 3 : Apakah cuaca mempengaruhi jumlah berat sampah yang dihasilkan?
"""

berat_per_cuaca = df.groupby('cuaca')['berat_kg'].mean().sort_values(ascending=False).reset_index()

plt.figure(figsize=(10, 6))
ax = sns.barplot(
    x='cuaca',
    y='berat_kg',
    data=berat_per_cuaca,
    palette='Set2'
)

for p in ax.patches:
    ax.annotate(f"{p.get_height():.1f} Kg",
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center',
                xytext=(0, 10),
                textcoords='offset points',
                fontsize=11, fontweight='bold', color='#34495e')

mean_berat = df['berat_kg'].mean()
plt.axhline(mean_berat, color='#e74c3c', linestyle='--', linewidth=2, label=f'Rata-rata Keseluruhan ({mean_berat:.1f} Kg)')

plt.title('Rata-rata Berat Sampah Berdasarkan Kondisi Cuaca', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Kondisi Cuaca', fontsize=12)
plt.ylabel('Rata-rata Berat Sampah (Kg)', fontsize=12)
plt.ylim(0, berat_per_cuaca['berat_kg'].max() * 1.15)

plt.gca().spines['top'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.legend(loc='upper right')
plt.tight_layout()
plt.show()

"""### Insight:
Analisis untuk pertanyaan ketiga, `Apakah cuaca mempengaruhi jumlah berat sampah yang dihasilkan?`, menunjukkan bahwa meskipun ada sedikit perbedaan rata-rata berat sampah antara kondisi cuaca `cerah`, `hujan`, dan `mendung`, perbedaannya tidak terlalu signifikan. Bar plot juga menunjukkan distribusi rata-rata berat sampah yang serupa di ketiga kategori cuaca. Ini menyiratkan bahwa cuaca mungkin bukan faktor utama yang mempengaruhi *jumlah* berat sampah secara drastis, meskipun mungkin ada pengaruh pada *jenis* sampah atau pola pengumpulan.

### Kesimpulan:
Berdasarkan analisis data sampah yang telah dilakukan, ada beberapa kesimpulan:

1.  **Kecamatan Penyumbang Sampah Terbesar:** Kecamatan **Cilandak** teridentifikasi sebagai penyumbang berat sampah tertinggi, diikuti oleh Pasar Minggu dan Cengkareng. Hal ini menunjukkan perlunya fokus dan strategi pengelolaan sampah yang lebih intensif di wilayah-wilayah tersebut.

2.  **Jenis Sampah Dominan dan Pengelolaan:** Sampah **organik** adalah jenis sampah yang paling dominan dalam dataset. Metode pengelolaan yang paling sering tercatat untuk sampah organik adalah `bank sampah`, `dibakar`, dan `daur ulang`, dengan `kompos` juga memiliki proporsi yang signifikan. Untuk mengelola sampah organik secara lebih efektif dan berkelanjutan, metode seperti pengomposan atau produksi biogas dapat menjadi prioritas. Selain itu, proporsi sampah anorganik seperti kertas dan plastik yang signifikan menekankan pentingnya program daur ulang yang terstruktur dan edukasi masyarakat mengenai pemilahan sampah di sumbernya.

3.  **Pengaruh Cuaca:** Analisis menunjukkan bahwa kondisi cuaca (cerah, hujan, mendung) memiliki **pengaruh yang tidak signifikan** terhadap jumlah berat sampah yang dihasilkan. Fluktuasi berat sampah cenderung stabil terlepas dari kondisi cuaca, menunjukkan bahwa faktor lain mungkin lebih berpengaruh terhadap volume sampah harian.

Secara keseluruhan, temuan ini memberikan dasar bagi pemerintah daerah dan pemangku kepentingan lainnya untuk merancang kebijakan dan program pengelolaan sampah yang lebih tepat sasaran, dengan memprioritaskan area dan jenis sampah tertentu, serta mengoptimalkan strategi berdasarkan karakteristik data yang ada.
"""