# -*- coding: utf-8 -*-
"""Project_capstone_baru.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCrNeRJyb7hd8iqbkxIy-vtCUhypk7up

# Menentukan Pertanyaan Bisnis

- Pertanyaan 1: Apakah dataset gambar sampah yang tersedia sudah cukup berkualitas dan seimbang untuk menghasilkan model klasifikasi yang akurat?
- Pertanyaan 2: Kategori sampah apa yang paling sering muncul dan fitur apa yang paling penting untuk ditampilkan di website?

# Import Library/Packages yang Digunakan
"""

import pandas as pd
import numpy as np
import os
import shutil
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image, ImageOps, ImageEnhance
from tqdm.notebook import tqdm
from sklearn.utils import resample
from concurrent.futures import ProcessPoolExecutor
from concurrent.futures import ThreadPoolExecutor
from sklearn.model_selection import train_test_split
from google.colab import drive

# Konfigurasi Google Drive
drive.mount('/content/drive')

"""# Gathering Data"""

path_1 = '/content/drive/MyDrive/Dataset/archive/original'
path_2 = '/content/drive/MyDrive/Dataset/archive_1/images/images'
path_3 = '/content/drive/MyDrive/Dataset/archive_2'
path_4 = '/content/drive/MyDrive/Dataset/archive_3/balanced_waste_images'
path_5 = '/content/drive/MyDrive/Dataset/archive_3/Garbage_Classification'
path_6 = '/content/drive/MyDrive/Dataset/archive/garbage_classification'
path_7 = '/content/drive/MyDrive/Dataset/archive_3/Medical'

def gathering_simple(paths):
    data_list = []

    valid_ext = ('.png', '.jpg', '.jpeg')

    print("Mengambil data dari Drive...")
    for root_path in paths:
        if not os.path.exists(root_path): continue
        for root, dirs, files in os.walk(root_path):
            folder_name = os.path.basename(root)
            for f in files:
                if f.lower().endswith(valid_ext):
                    full_p = os.path.join(root, f)
                    try:
                        size_kb = os.path.getsize(full_p) / 700
                        data_list.append([full_p, folder_name, size_kb])
                    except: continue
    return pd.DataFrame(data_list, columns=['file_path', 'sub_category', 'size_kb'])

df_raw = gathering_simple([path_1, path_2, path_3, path_4, path_5, path_6,path_7])
print(f"Gathering Selesai: {len(df_raw)} data terkumpul")
df_raw.head(5)

"""# Wrangling (Accessing Data)"""

def profiling_report(df, title="LAPORAN DATA"):
    print(f"\n{'='*20} {title} {'='*20}")

    # 1. Pemeriksaan Tipe Data
    print("\n1. Pemeriksaan Tipe Data (info):")
    df.info()

    # 2. Pemeriksaan Missing Values
    print("\n2. Pemeriksaan Missing Values (Null):")
    print(df.isnull().sum())

    # 3. Pemeriksaan Data Duplikat (Baris Tabel)
    print("\n3. Pemeriksaan Data Duplikat (Identitas Baris):")
    print(f"Jumlah baris duplikat di tabel: {df.duplicated().sum()}")

    # 4. Ringkasan Parameter Statistik
    print("\n4. Ringkasan Parameter Statistik (size_kb):")
    print(df['size_kb'].describe())
    print("="*55)

# Jalankan untuk Data Mentah
profiling_report(df_raw, title="TAHAP ASSESSING: PROFIL DATA MENTAH")

"""**Steps to Take:**

- Mengumpulkan data gambar mentah dari berbagai direktori Google Drive yang telah ditentukan (`path_1` hingga `path_7`).
- Melakukan profiling awal terhadap data mentah yang terkumpul (`df_raw`) untuk memeriksa tipe data, missing values, duplikasi baris, dan ringkasan statistik `size_kb`.

**Insight:**

- Dataset mentah (`df_raw`) tidak memiliki missing values atau duplikasi baris, menunjukkan kualitas data yang baik pada tahap awal pengumpulan.
- Kolom `size_kb` memiliki distribusi yang cukup lebar, dengan ukuran file rata-rata sekitar 43.7 KB dan maksimum mencapai lebih dari 6 MB, yang menunjukkan variasi ukuran gambar yang perlu dipertimbangkan untuk pemrosesan lebih lanjut.

# Cleaning Data
"""

def remove_duplicate_images(df):

    print("\nTahap Remove Duplikat")

    unique_files = set()

    cleaned_rows = []

    duplicate_rows = []

    print("\n" + "=" * 40)
    print("Data Sebelum Remove Duplikatt")
    print("=" * 40)

    print(
        df['label']
        .value_counts()
    )

    print(f"Total Data Sebelum Duplikat : {len(df)}")

    for _, row in df.iterrows():

        try:

            file_path = row['file_path']

            file_name = os.path.basename(file_path)

            file_size = os.path.getsize(file_path)

            unique_id = (
                file_name,
                file_size
            )

            if unique_id not in unique_files:

                unique_files.add(unique_id)

                cleaned_rows.append(row)

            else:

                duplicate_rows.append(row)

        except:
            continue

    df_cleaning = pd.DataFrame(cleaned_rows)

    df_duplicate = pd.DataFrame(duplicate_rows)

    print("\n" + "=" * 40)
    print("Data Sesudah Remove Duplikat")
    print("=" * 40)

    print(
        df_cleaning['label']
        .value_counts()
    )

    print(f"Total Data Sesudah Duplikat : {len(df_cleaning)}")

    print(f"Total Duplikat : {len(df_duplicate)}")

    return df_cleaning, df_duplicate


def cleaning_and_annotation(df):

    print("TAHAP CLEANING & ANNOTATION")

    print("\n" + "=" * 40)
    print("DATA AWAL GATHERING")
    print("=" * 40)

    print(f"TOTAL DATA RAW : {len(df)}")

    df['sub_category'] = (
        df['sub_category']
        .astype(str)
        .str.strip()
        .str.lower()
    )

    mapping = {

        'battery': 'B3',
        'battery_3': 'B3',
        'batterys_3': 'B3',

        'keyboard': 'B3',
        'keyboard_3': 'B3',

        'microwave': 'B3',
        'microwave_3': 'B3',

        'mobile': 'B3',
        'mobile_3': 'B3',

        'mouse': 'B3',
        'mouse_3': 'B3',

        'pcb': 'B3',
        'pcb_3': 'B3',

        'printer': 'B3',

        'television': 'B3',
        'television_3': 'B3',

        'washing machine': 'B3',
        'washing machine_3': 'B3',

        'player': 'B3',
        'soundplayer_3': 'B3',

        'e-waste': 'B3',

        'mask': 'B3',
        'mask_3': 'B3',

        'gloves': 'B3',
        'gloves_3': 'B3',

        'medical_cap': 'B3',
        'medical_glasses': 'B3',

        'gauze': 'B3',

        'body_tissue_or_organ': 'B3',

        'syringe': 'B3',
        'syringe_needle': 'B3',

        'test_tube': 'B3',

        'tweezers': 'B3',

        'urine_bag': 'B3',

        'glove_pair_latex': 'B3',
        'glove_pair_nitrile': 'B3',
        'glove_pair_surgery': 'B3',

        'glove_single_latex': 'B3',
        'glove_single_nitrile': 'B3',
        'glove_single_surgery': 'B3',

        'shoe_cover_pair': 'B3',
        'shoe_cover_single': 'B3',

        'aerosol_cans': 'B3',

        'biological': 'Organik',

        'organic': 'Organik',
        'organik': 'Organik',
        'organics': 'Organik',
        'organic_3': 'Organik',

        'food_waste': 'Organik',
        'organic_waste': 'Organik',

        'coffee_grounds': 'Organik',

        'eggshells': 'Organik',

        'sayuran': 'Organik',

        'trash': 'Organik',
        'trash_3': 'Organik',
        'trashes': 'Organik',
        'trashs_b3': 'Organik',

        'cardboard': 'Anorganik',
        'cardboard_3': 'Anorganik',
        'cardboards': 'Anorganik',
        'cardboardes_3': 'Anorganik',

        'cardboard_boxes': 'Anorganik',
        'cardboard_packaging': 'Anorganik',

        'clothes': 'Anorganik',
        'clothess_3': 'Anorganik',

        'clothing': 'Anorganik',

        'textile': 'Anorganik',

        'shoes': 'Anorganik',

        'glass': 'Anorganik',
        'glass_3': 'Anorganik',

        'glasses': 'Anorganik',
        'glasses_3': 'Anorganik',

        'brown-glass': 'Anorganik',
        'green-glass': 'Anorganik',
        'white-glass': 'Anorganik',

        'glass_beverage_bottles': 'Anorganik',
        'glass_cosmetic_containers': 'Anorganik',
        'glass_food_jars': 'Anorganik',

        'glass_equipment_packaging': 'Anorganik',

        'paper': 'Anorganik',
        'paper_3': 'Anorganik',

        'papers': 'Anorganik',
        'papers_3': 'Anorganik',

        'newspaper': 'Anorganik',

        'magazines': 'Anorganik',

        'office_paper': 'Anorganik',

        'paper_cups': 'Anorganik',

        'paper_equipment_packaging': 'Anorganik',

        'plastic': 'Anorganik',
        'plastic_3': 'Anorganik',

        'plastics_3': 'Anorganik',

        'plastic_botol': 'Anorganik',
        'plastic_botle': 'Anorganik',

        'plastic_cup_lids': 'Anorganik',

        'plastic_detergent_bottles': 'Anorganik',

        'plastic_food_containers': 'Anorganik',

        'plastic_shopping_bags': 'Anorganik',

        'plastic_soda_bottles': 'Anorganik',

        'plastic_straws': 'Anorganik',

        'plastic_trash_bags': 'Anorganik',

        'plastic_water_bottles': 'Anorganik',

        'plastic_equipment_packaging': 'Anorganik',

        'metal': 'Anorganik',
        'metal_3': 'Anorganik',

        'metals': 'Anorganik',
        'metals_3': 'Anorganik',

        'aluminum_food_cans': 'Anorganik',

        'aluminum_soda_cans': 'Anorganik',

        'metal_equipment_packaging': 'Anorganik',
    }

    df['label'] = df['sub_category'].map(mapping)

    df_cleaning = df.dropna(
        subset=['label']
    ).copy()

    print("\n" + "=" * 40)
    print("SETELAH MAPPING LABEL")
    print("=" * 40)

    print(
        df_cleaning['label']
        .value_counts()
    )

    print(f"\nTOTAL SETELAH MAPPING : {len(df_cleaning)}")

    df_cleaning, df_duplicate = remove_duplicate_images(
        df_cleaning
    )

    TARGETS = {
        'B3': 3300,
        'Organik': 3300,
        'Anorganik': 3400
    }

    balanced_data = []

    print("\n" + "=" * 40)
    print("BALANCING DATA")
    print("=" * 40)

    for label, target in TARGETS.items():

        temp_df = df_cleaning[
            df_cleaning['label'] == label
        ]

        print(f"\n{label} sebelum balancing : {len(temp_df)}")

        if len(temp_df) < target:

            temp_balanced = resample(
                temp_df,
                replace=True,
                n_samples=target,
                random_state=42
            )

        else:

            temp_balanced = resample(
                temp_df,
                replace=False,
                n_samples=target,
                random_state=42
            )

        balanced_data.append(temp_balanced)

        print(f"{label} sesudah balancing : {len(temp_balanced)}")

    df_final = pd.concat(
        balanced_data
    )

    df_final = (
        df_final
        .sample(frac=1, random_state=42)
        .reset_index(drop=True)
    )

    print("\n" + "=" * 40)
    print("HASIL FINAL")
    print("=" * 40)

    print(
        df_final['label']
        .value_counts()
    )

    print("=" * 40)
    print(f"TOTAL DATA FINAL : {len(df_final)}")

    return df_final, df_cleaning, df_duplicate


df_final, df_cleaning, df_duplicate = cleaning_and_annotation(df_raw)

"""**Insight:**

- Sebanyak 42.276 gambar berhasil dianotasi dan dikategorikan ke dalam 'Anorganik', 'B3', dan 'Organik', menunjukkan keberhasilan proses pembersihan dan pelabelan data.
- Terdapat ketidakseimbangan yang signifikan dalam distribusi kategori sampah, di mana 'Anorganik' mendominasi dengan jumlah tertinggi, diikuti oleh 'B3' dan 'Organik'. Hal ini perlu dipertimbangkan dalam tahap pengembangan model untuk menghindari bias.

## EDA (Exploratory Data Analysis) ##
"""

sns.set(style="whitegrid")
plt.rcParams["figure.figsize"] = (10,6)

# Dataset
df = df_final.copy()

print("Jumlah Baris dan Kolom :", df.shape)
display(df.head())

print("\nInfo Dataset")
df.info()

print("\nMissing Value")
display(df.isnull().sum())

"""**Insight:**

- Setelah proses cleaning dan anotasi, `df_final` tidak memiliki missing values atau duplikasi, menandakan data siap untuk analisis lebih lanjut.
- Distribusi kategori sampah sangat tidak seimbang, dengan 'Anorganik' menjadi kategori yang paling banyak, yang merupakan observasi penting untuk pengembangan model.

## Visualization & Explanatory Analysis
"""

plt.figure(figsize=(8,5))
sns.countplot(data=df, x="label", palette="Set2")

plt.title("Distribusi Kategori Sampah")
plt.xlabel("Kategori")
plt.ylabel("Jumlah Data")
plt.show()

"""Persentase Kategori Sampah"""

df["label"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%",
    startangle=90,
    cmap="Pastel1",
    figsize=(7,7)
)

plt.title("Persentase Kategori Sampah")
plt.ylabel("")

plt.show()

"""Pertanyaan 2: Kategori sampah apa yang paling sering muncul dan fitur apa yang paling penting untuk ditampilkan di website?"""

top10 = df["sub_category"].value_counts().head(10)

plt.figure(figsize=(12,6))

sns.barplot(
    x=top10.index,
    y=top10.values,
    palette="Blues_r"
)

plt.title("Top 10 Jenis Sampah Terbanyak")
plt.xlabel("Jenis Sampah")
plt.ylabel("Jumlah")

plt.xticks(rotation=45)

plt.show()

"""Distribusi Ukuran File"""

plt.figure(figsize=(8,5))

sns.histplot(
    df["size_kb"],
    bins=50,
    kde=True,
    color="orange"
)

plt.xscale("log")

plt.title("Distribusi Ukuran File (Log Scale)")
plt.xlabel("Ukuran File KB (Log)")
plt.ylabel("Frekuensi")

plt.show()

"""Ukuran File per Kategori"""

plt.figure(figsize=(8,5))

sns.boxplot(
    data=df,
    x="label",
    y="size_kb",
    hue="label",
    palette="Set3",
    legend=False,
    showfliers=False
)

plt.yscale("log")

plt.title("Ukuran File per Kategori")
plt.xlabel("Kategori")
plt.ylabel("Ukuran KB (Log)")

plt.show()

"""Heatmap Sub Category vs Label"""

cross = pd.crosstab(
    df["sub_category"],
    df["label"]
)

cross_pct = cross.div(cross.sum(axis=1), axis=0)

plt.figure(figsize=(10,8))

sns.heatmap(
    cross_pct,
    cmap="YlGnBu",
    linewidths=0.5
)

plt.title("Heatmap Persentase Sub Category vs Label")
plt.xlabel("Label")
plt.ylabel("Sub Category")

plt.show()

"""**Insight:**

- Visualisasi distribusi kategori sampah (diagram batang dan pie chart) mengkonfirmasi dominasi kategori 'Anorganik', diikuti oleh 'B3' dan 'Organik', yang mengindikasikan perlunya strategi penanganan ketidakseimbangan kelas saat pelatihan model.
- Diagram batang 'Top 10 Jenis Sampah Terbanyak' menunjukkan sub-kategori spesifik yang paling sering muncul, memberikan informasi berharga untuk desain fitur atau fokus pengenalan model.
- Distribusi ukuran file `size_kb` menunjukkan variasi yang signifikan, dengan mayoritas gambar berukuran kecil namun ada juga outlier besar. Boxplot ukuran file per kategori juga menunjukkan perbedaan distribusi ukuran file antar kategori utama.
- Heatmap `Sub Category vs Label` secara efektif memvisualisasikan bagaimana setiap sub-kategori dipetakan ke label utama, memvalidasi proses anotasi.

### Train dan Test
"""

main_data = df_final.copy()

print(main_data.shape)
main_data.head()

from google.colab import drive
drive.mount('/content/drive')

from sklearn.model_selection import train_test_split


train_df, temp_df = train_test_split(
    df_final,
    test_size=0.3,
    random_state=42,
    stratify=df_final["label"]
)


test_df, val_df = train_test_split(
    temp_df,
    test_size=1/3,
    random_state=42,
    stratify=temp_df["label"]
)

# Output jumlah data
print(f"Data Train      : {len(train_df)} gambar")
print(f"Data Test       : {len(test_df)} gambar")
print(f"Data Validation : {len(val_df)} gambar")

base_output = "/content/Dataset_Final_Cleaned"

labels = df_final['label'].unique()

for subset in ['train', 'test', 'validation']:

    for label in labels:

        folder_path = os.path.join(
            base_output,
            subset,
            str(label)
        )

        os.makedirs(
            folder_path,
            exist_ok=True
        )

print("Struktur folder berhasil dibuat!")

def finalize_dataset(df, subset_name):

    print(f"\nMemproses Dataset: {subset_name}")

    success = 0
    failed = 0

    total_data = len(df)

    target_base = os.path.join(
        base_output,
        subset_name
    )

    os.makedirs(
        target_base,
        exist_ok=True
    )

    for idx, row in df.iterrows():

        try:

            source = row['file_path']
            label = str(row['label'])

            target_dir = os.path.join(
                target_base,
                label
            )

            os.makedirs(
                target_dir,
                exist_ok=True
            )

            with Image.open(source) as img:

                img = img.convert("RGB")

                img = img.resize((224, 224))

                target_path = os.path.join(
                    target_dir,
                    f"img_{idx}.jpg"
                )

                img.save(
                    target_path,
                    format="JPEG",
                    quality=85
                )

            success += 1

        except:

            failed += 1

        processed = success + failed

        if processed % 50 == 0 or processed == total_data:

            progress = (
                processed / total_data
            ) * 100

            print(
                f"Progress: {progress:.2f}% "
                f"({processed}/{total_data})"
            )

    print(f"\n{subset_name.upper()} selesai")
    print(f"Berhasil : {success}")
    print(f"Gagal    : {failed}")

finalize_dataset(
    train_df,
    "train",

)

finalize_dataset(
    val_df,
    "validation",

)

finalize_dataset(
    test_df,
    "test",

)

print("Dataset final berhasil dirapikan!")

"""**Insight:**

- Data berhasil dibagi menjadi Train (80%) dan Test (20%) menggunakan `train_test_split`.
- Penggunaan `stratify` memastikan bahwa proporsi setiap kategori sampah (`Anorganik`, `B3`, `Organik`) dipertahankan secara seimbang di kedua set data, yang sangat penting mengingat adanya ketidakseimbangan kelas.
- Struktur folder output untuk data latih dan uji berhasil dibuat dan semua gambar telah disalin ke direktori yang sesuai, siap untuk proses pelatihan model.

# CEK HASIL DATA
"""

# Cek hasil Datasetnya
def cek_hasil_dataset(base_output):
    """
    Menampilkan jumlah file pada setiap subset dan label
    """

    total_semua = 0

    for subset in ['train', 'validation', 'test']:

        subset_path = os.path.join(base_output, subset)

        print(f"\nSUBSET: {subset.upper()}")

        if not os.path.exists(subset_path):
            print("Folder tidak ditemukan")
            continue

        total_subset = 0

        for label in os.listdir(subset_path):

            label_path = os.path.join(subset_path, label)

            if os.path.isdir(label_path):

                jumlah_file = len([
                    f for f in os.listdir(label_path)
                    if os.path.isfile(os.path.join(label_path, f))
                ])

                total_subset += jumlah_file

                print(f"   {label:<15} : {jumlah_file} file")

        total_semua += total_subset

        print(f"Total {subset:<10}: {total_subset} file")

    print(f"\nTOTAL SEMUA FILE: {total_semua}")

cek_hasil_dataset(base_output)

"""# Mengubah Folder ke .zip

"""

!zip -r Dataset_Final_Cleaned.zip /content/Dataset_Final_Cleaned